plugin:
    name: Myhome
    description: 'fiveupmedia.myhome::lang.plugin.description'
    author: FiveUpMedia
    icon: oc-icon-home
    homepage: ''
navigation:
    main-menu-item:
        label: 'fiveupmedia.myhome::lang.plugin.name'
        url: fiveupmedia/myhome/operations
        icon: icon-home
        sideMenu:
            side-menu-item:
                label: Appartamenti
                url: fiveupmedia/myhome/apartments
                icon: icon-list
            side-menu-item2:
                label: Operazioni
                url: fiveupmedia/myhome/operations
                icon: icon-list
            side-menu-item3:
                label: Unità
                url: fiveupmedia/myhome/units
                icon: icon-list
