list: $/fiveupmedia/myhome/models/apartment/columns.yaml
modelClass: Fiveupmedia\Myhome\Models\Apartment
title: Apartments
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fiveupmedia/myhome/apartments/update/:id'
